# Site settings
title: Keerthan Jaic
email: jckeerthan@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jck.io" # the base hostname & protocol for your site
github_username:  jck

permalink: /:year/:month/:title

exclude: ['gems.rb', 'gems.locked', 'Makefile']
include: ['.well-known']

theme: minima
google_analytics: UA-63900578-1
